In [1]:
import pandas as pd

In [ ]:
smart_watches =  pd.read_csv('C:/Users/HP/.cache/kagglehub/datasets/rkiattisak/smart-watch-prices/versions/1/smart watch prices.csv',
                             index_col=0)

pd.set_option('display.max_rows',4) # Display maximum 4 rows of a dataframe

smart_watches

,Model,Operating System,Connectivity,Display Type,Display Size (inches),Resolution,Water Resistance (meters),Battery Life (days),Heart Rate Monitor,GPS,NFC,Price (USD)
Brand,,,,,,,,,,,,
Apple,Watch Series 7,watchOS,"Bluetooth, Wi-Fi, Cellular",Retina,1.90,396 x 484,50,18,Yes,Yes,Yes,$399
Samsung,Galaxy Watch 4,Wear OS,"Bluetooth, Wi-Fi, Cellular",AMOLED,1.40,450 x 450,50,40,Yes,Yes,Yes,$249
...,...,...,...,...,...,...,...,...,...,...,...,...
Oppo,Watch Free,ColorOS,"Bluetooth, Wi-Fi",AMOLED,1.64,326 x 326,50,14,Yes,No,Yes,$159
TicWatch,Pro 3,Wear OS,"Bluetooth, Wi-Fi, Cellular",AMOLED,1.40,454 x 454,50,72,Yes,Yes,Yes,$299